### ISSUE TITLE
Некорректные координаты одной из точек линии кратчайшего расстояния между точкой и полилинией

### ISSUE THREAD

**Issue by done-eagle** [gems-development/geos-gempix#16]
Подробнее в разделе с ошибками:
https://docs.google.com/spreadsheets/d/1ZJtm3sl9jjyeYXwqxv6gpGiCeyU8ixppI-QlPGEgm8s/edit#gid=616911898

**Comment by DenisKamaliev** [comment]
Нашёл в чём проблема:  не правильно считается точка, через которую должен проходить перпендикуляр 
К примеру для точки (0;2) и линии y=x точка, куда опускается перпендикуляр должна иметь координаты (1;1), но программа считает (-1;-1). Решение пока в процессе
